version: "3"

services:
  web:
    image: "php:8.3-apache"
    depends_on:
      - mariadb
    restart: 'always'
    ports:
      - '8080:80'
      - '8443:443'
    links:
      - mariadb
    volumes:
      - ../:/var/www/html
  mariadb:
    image: "mariadb:11.4"
    restart: 'always'
    volumes:
      - dbdata:/var/lib/mysql"
    ports:
      - '13306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
volumes:
  dbdata: