version: "3.9"

x-podman:
  podman-pod:
    name: biznizz

services:
  web:
    image: "php:8.3-apache"
    depends_on:
      - mariadb
    restart: 'always'
    ports:
      - '8080:80'
      - '8443:443'
    volumes:
      - ../:/var/www/html
      - apache/sites-available/default.conf:/etc/apache2/sites-available/default.conf
      - apache/ssl:/etc/apache2/ssl
    environment:
      # Optional, falls du php.ini oder Module brauchst
      # Beispiel: PHP_MEMORY_LIMIT: 512M
    networks:
      - backend

  mariadb:
    image: "mariadb:11.4"
    restart: 'always'
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - '13306:3306'
    env_file:
      - ../.env
    environment:
      MARIADB_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MARIADB_DATABASE: "${MYSQL_DATABASE}"
      MARIADB_USER: "${MYSQL_USER}"
      MARIADB_PASSWORD: "${MYSQL_PASSWORD}"
    networks:
      - backend

volumes:
  dbdata:

networks:
  backend:
